import { useQuery } from '@tanstack/react-query';

import { api } from '@/lib/api';
import type { ApiListEnvelope } from '@/types/api';
import type { Movimiento } from '@/features/movimientos/types';

// Movimientos generated by a venta (GET /movimientos?venta_id=).
export function useVentaMovimientos(ventaId: number) {
  return useQuery({
    queryKey: ['movimientos', 'venta', ventaId],
    queryFn: async () => {
      const res = await api.get<ApiListEnvelope<Movimiento>>('/movimientos', {
        params: { venta_id: ventaId, page_size: 50 },
      });
      return res.data.data;
    },
    enabled: Number.isFinite(ventaId) && ventaId > 0,
  });
}
